# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/lynx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lynx)

$(call add-radio-file-sha1-checked,radio/abl.img,db6f367c6166868d36dcef777e006b02666ea44d)
$(call add-radio-file-sha1-checked,radio/bl1.img,0b11ffc66dfd329bfc4b26079221bb0dfcb7fb11)
$(call add-radio-file-sha1-checked,radio/bl2.img,81890a9a9aba89cca1465d5f2277cf14620317e7)
$(call add-radio-file-sha1-checked,radio/bl31.img,f6ce3feca201238d4ce4e608f229bf103e712458)
$(call add-radio-file-sha1-checked,radio/gsa.img,033593406ef5566113ee385fa7e9d9404560c205)
$(call add-radio-file-sha1-checked,radio/ldfw.img,0540b232af85b5d92ea2d2e45c7774747fb57c46)
$(call add-radio-file-sha1-checked,radio/modem.img,69eda14708197f30b8b680d15c855cad2371f4f2)
$(call add-radio-file-sha1-checked,radio/pbl.img,fbaedcec025ac65d41ad9d3cb423b55111471ef5)
$(call add-radio-file-sha1-checked,radio/tzsw.img,7c76c0b9eb4e283d80188e202ee530d3ff5e3cde)

endif
