# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/lynx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lynx)

$(call add-radio-file-sha1-checked,radio/abl.img,00d64826e34fe15e5f12cbc629b5ef561c960c1f)
$(call add-radio-file-sha1-checked,radio/bl1.img,c0f58a7131dd96c52a5815b39e60f5f618068ca0)
$(call add-radio-file-sha1-checked,radio/bl2.img,60d2afd6ab65b7ab5432f49e33b9fe0c373d0bde)
$(call add-radio-file-sha1-checked,radio/bl31.img,d465dccac3639d414f329c4771ad4780d9430241)
$(call add-radio-file-sha1-checked,radio/gsa.img,5a9d01da7f79e03639bb0e9e84e0f8615cb64e7d)
$(call add-radio-file-sha1-checked,radio/ldfw.img,21396276155c332ed2c2978eb658de60921dcfd6)
$(call add-radio-file-sha1-checked,radio/modem.img,45165132f58377117fd2e7bb594cd48692b4b27a)
$(call add-radio-file-sha1-checked,radio/pbl.img,8cebee1f04f8d1f250e590e614144b205eb2d799)
$(call add-radio-file-sha1-checked,radio/tzsw.img,e1756538d98a1d1741c137fe5c6a6f60ef1202ba)

endif
